### ISSUE TITLE
How do I build and run this app?

### ISSUE THREAD

**Issue by rebelliard** [RIAEvangelist/electron-video-player#29]
I'm new to electron...

**Comment by RIAEvangelist** [comment]
I need to update the build process.

**Comment by RIAEvangelist** [comment]
will take care of it in the next 24 hours

**Comment by jmstacey** [comment]
I got it up and running doing something like this on macOS with [Homebrew](http://brew.sh).
1. `brew cask install electron`
2. `git clone https://github.com/RIAEvangelist/electron-video-player.git`
3. `/Applications/Electron.app/Contents/MacOS/Electron electron-video-player/src`

**Comment by RIAEvangelist** [comment]
FYI you can just download the package for your platform here :

https://github.com/RIAEvangelist/electron-video-player/releases/tag/v1.0.0

I'm working on converting it over to electron-builder
